#!/bin/bash
yes | cp /root/MyConfig/JDScripts/Cookie.json /root/JDScripts/Cookie.json
cd /root/JDScripts/
node jd_bean_change.js
node jd_bean_home.js
node jd_beauty.js
node jd_blueCoin.js
node jd_car.js
node jd_car_exchange.js
node jd_car_notify.js
node jd_cash.js
node jd_cash_exchange.js
node jd_cfd.js
node jd_cfdtx.js
node jd_club_lottery.js
node jd_daily_egg.js
node jd_daily_lottery.js
node jd_djjl.js
node jd_dpqd.js
node jd_DrawEntrance.js
node jd_dreamFactory_tuan.js
node jd_family.js
node jd_flipcards.js
node jd_gold_creator.js
node jd_goodMorning.js
node jd_half_redrain.js
node jd_health.js
node jd_health_collect.js
node jd_jdfactory.js
node jd_jdzz.js
node jd_jintie.js
node jd_joy.js
node jd_joy_help.js
node jd_joy_park.js
node jd_joy_park_open.js
node jd_joy_park_task.js
node jd_joy_reward.js
node jd_joy_steal.js
node jd_jxlhb.js
node jd_kd.js
node jd_kj.js
node jd_live.js
node jd_live_redrain.js
node jd_lotteryMachine.js
node jd_market_lottery.js
node jd_MMdou.js
node jd_mohe.js
node jd_moneyTree.js
node jd_moneyTree_help.js
node jd_ms.js
node jd_necklace.js
node jd_NewSign.js
node jd_nzmh.js
node jd_paoku.js
node jd_pigPet.js
node jd_plantBean.js
node jd_ppdz.js
node jd_priceProtect.js
node jd_qjd.js
node jd_rankingList.js
node jd_redPacket.js
node jd_sendBeans.js
node jd_sgmh.js
node jd_shake.js
node jd_shop.js
node jd_shoplottery.js
node jd_sign_validate.js
node jd_small_home.js
node jd_speed.js
node jd_speed_redpocke.js
node jd_speed_sign.js
node jd_summer_mom_opencard.js
node jd_summer_movement.js
node jd_summer_movement_help.js
node jd_superMarket.js
node jd_super_redrain.js
node jd_syj.js
node jd_unsubscribe.js
node jd_wishingPool.js
node jd_wsdlb.js
node jd_wxj.js
node jd_zjb.js
node jx_sign.js
